Classe d'age ou les symptomes Prodormaux sont les plus fréquents

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('C:\\Users\\jorda\\PycharmProjects\\Aicha_These\\data\\Thesis_Aicha_Data V3.csv', sep=";")

df

,Sexe,Mode_entree_note,Mode_entree,Age_debut_symptomes,Symptomes_prodromaux,TCSP_prodr,Syndrome_extrapyramidal,Delai_syndrome_extrapyramidal,Symptomes_cognitifs,Date_symptomes_cognitifs,Symptomes_psychiatriques,Delai_symptomes_psychiatriques,Trouble_oculomoteur,Symptomes_moteurs,Idees_delirantes,Delai_fluctuations,Nom Mode_entree,Tranche_age
0,Feminin,"Troubles mnésiques, désorientation",Trouble Cognitfs,78.0,Non,Non,Oui,"0,5",1.0,0,Oui,"0,5",Non,Oui,Non,0.0,Trouble Cognitfs,77-100
1,Masculin,Cognitif (2010) : troubles mnésiques,Trouble Cognitfs,63.0,Oui,Oui,Non,NaN,1.0,0,Oui,6,NSP,Non,NaN,7.0,Trouble Cognitfs,0-65
2,Masculin,Cognitif (2013) : troubles dyséxécutifs,Trouble Cognitfs,58.0,NaN,Oui,Oui,4,1.0,0,Oui,3,NSP,NaN,NaN,3.0,Trouble Cognitfs,0-65
3,Masculin,Cognitif (2012) : troubles du langage et de la...,Trouble Cognitfs,52.0,Oui,Oui,Oui,0,1.0,0,Oui,2,NSP,Oui,NaN,1.0,Trouble Cognitfs,0-65
4,Feminin,Psychiatrique (2016) : troubles du comportemen...,Trouble Psychatrique,71.0,NaN,NaN,Non,NaN,1.0,1,Oui,0,NSP,Non,Oui,NaN,Trouble Psychatrique,66-75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Masculin,Plainte cognitive,Trouble Cognitfs,76.0,NaN,NaN,Oui,NaN,1.0,0,Oui,NaN,NaN,Oui,Oui,NaN,Trouble Cognitfs,77-100
106,Masculin,Plainte cognitive,Trouble Cognitfs,48.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trouble Cognitfs,0-65
107,Masculin,Plainte cognitive,Trouble Cognitfs,52.0,NaN,NaN,Oui,3,1.0,0,Oui,NaN,NaN,Oui,Oui,3.0,Trouble Cognitfs,0-65
108,Masculin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Masculin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df2=df[['Symptomes_prodromaux','Tranche_age']]

In [3]:
df2=df2.dropna()

In [4]:
df2

    Symptomes_prodromaux Tranche_age
0                    Non      77-100
1                    Oui        0-65
3                    Oui        0-65
5                    Non       66-75
6                    Oui       66-75
7                    Non       66-75
9                    Non       66-75
10                   Non       66-75
13                   Non       66-75
14                   Oui       66-75
15                   Oui        0-65
16                   Oui        0-65
17                   Non       66-75
19                   Oui       66-75
20                   Oui        0-65
22                   Oui        0-65
23                   Oui      77-100
25                   Oui        0-65
30                   Non       66-75
31                   Non        0-65
33                   Non        0-65
34                   Oui        0-65
35                   Oui        0-65
36                   Oui        0-65
38                   Oui        0-65
39                   Oui       66-75
40                   Oui       66-75
41                   Non      77-100
42                   Oui       66-75
43                   Non       66-75
45                   Non       66-75
49                   Oui        0-65
50                   Oui       66-75
51                   Oui      77-100
58                   Oui      77-100
59                   Oui       66-75
60                   Oui       66-75
61                   Non      77-100
64                   Oui       66-75
68                   Non      77-100
69                   Oui       66-75
76                   Non      77-100
77                   Oui       66-75
79                   Oui       66-75
81                   Non       66-75
82                   Non       66-75
86                   Oui       66-75
88                   Oui        0-65
91                   Oui       66-75
92                   Oui       66-75
98                   Oui      77-100
100                  Oui      77-100
103                  Oui        0-65
104                  Oui      77-100

In [5]:
prodormaux=df2[df2['Symptomes_prodromaux']=='Oui']
prodormaux

    Symptomes_prodromaux Tranche_age
1                    Oui        0-65
3                    Oui        0-65
6                    Oui       66-75
14                   Oui       66-75
15                   Oui        0-65
16                   Oui        0-65
19                   Oui       66-75
20                   Oui        0-65
22                   Oui        0-65
23                   Oui      77-100
25                   Oui        0-65
34                   Oui        0-65
35                   Oui        0-65
36                   Oui        0-65
38                   Oui        0-65
39                   Oui       66-75
40                   Oui       66-75
42                   Oui       66-75
49                   Oui        0-65
50                   Oui       66-75
51                   Oui      77-100
58                   Oui      77-100
59                   Oui       66-75
60                   Oui       66-75
64                   Oui       66-75
69                   Oui       66-75
77                   Oui       66-75
79                   Oui       66-75
86                   Oui       66-75
88                   Oui        0-65
91                   Oui       66-75
92                   Oui       66-75
98                   Oui      77-100
100                  Oui      77-100
103                  Oui        0-65
104                  Oui      77-100

In [6]:
counts=prodormaux[['Symptomes_prodromaux','Tranche_age']].value_counts().reset_index(name='counts')

counts

  Symptomes_prodromaux Tranche_age  counts
0                  Oui       66-75      16
1                  Oui        0-65      14
2                  Oui      77-100       6

In [7]:
import plotly.express as px
fig = px.pie(
    counts,
    values='counts',
    names='Tranche_age',
    title= "Symptome Prodromaux par tranche d'age"
)
fig.show()